Repository planetarium/plds, pull requests merged in 2023-12, with the labels that each got.

#7 Primitive: Skeletons
  packages/theme/foundations/radii.ts
  packages/ui/index.tsx
  packages/ui/skeleton/README.md
  packages/ui/skeleton/index.tsx
  packages/ui/skeleton/utils.ts
  pnpm-lock.yaml
Labels: Small

#9 Features: Tooltip
  packages/theme/foundations/colors.ts
  packages/ui/Header.tsx
  packages/ui/index.tsx
  packages/ui/tooltip/README.md
  packages/ui/tooltip/index.tsx
Labels: Medium

#10 Features: Badge
  packages/ui/badge/Badge.tsx
  packages/ui/badge/BadgeDot.tsx
  packages/ui/badge/README.md
  packages/ui/badge/index.tsx
  packages/ui/badge/transition.ts
  packages/ui/index.tsx
Labels: Medium

#11 Features: Components > Theme
  packages/theme/components/button.ts
  packages/theme/components/index.ts
  packages/theme/components/input.ts
  packages/theme/index.ts
Labels: Extra Small

#12 Features: Radio
  packages/theme/components/index.ts
  packages/theme/components/radio.ts
Labels: Extra Small

#15 Features: Input
  packages/theme/components/input.ts
  packages/theme/foundations/colors.ts
  packages/theme/index.ts
  packages/theme/package.json
  packages/ui/index.tsx
  packages/ui/input/README.md
  packages/ui/input/index.tsx
  pnpm-lock.yaml
Labels: Medium

#16 impl: Button
  apps/docs/app/page.tsx
  packages/theme/components/button.ts
  packages/ui/button/README.md
  packages/ui/button/index.tsx
Labels: Medium

#17 Features: Test setup
  apps/docs/app/page.tsx
  packages/ui/button/README.md
  packages/ui/package.json
  packages/ui/skeleton/index.spec.tsx
  packages/ui/vitest.config.ts
  pnpm-lock.yaml
Labels: Extra Large
